"""Chart Endpoint (ADR-0026) - streams a chart image generated by the
Chart Generation Tool (mcp_servers/shared/tools/generate_chart.py) back to
the frontend. Any authenticated caller may fetch any chart_id (an
unguessable UUID) - charts aren't business-unit-owned data like KB
documents, mirroring mcp-shared's own permissive philosophy (ADR-0026's
Consequences). Thin HTTP adapter - see app/services/chart_service.py."""
import uuid

from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse

from app.api.v1.deps import get_current_user_id
from app.services import chart_service

router = APIRouter()


@router.get("/charts/{chart_id}")
async def get_chart(chart_id: uuid.UUID, user_id: uuid.UUID = Depends(get_current_user_id)):
    return StreamingResponse(chart_service.get_chart_stream(chart_id), media_type="image/png")
